/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as FieldReportingRouteImport } from './routes/field-reporting'
import { Route as HistoricalRouteImport } from './routes/historical'
import { Route as RainfallRouteImport } from './routes/rainfall'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AlertsIndexRouteImport } from './routes/alerts.index'
import { Route as AlertsAlertIdRouteImport } from './routes/alerts.$alertId'
import { Route as AlertsPreferencesRouteImport } from './routes/alerts.preferences'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldReportingRoute = FieldReportingRouteImport.update({
  id: '/field-reporting',
  path: '/field-reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalRoute = HistoricalRouteImport.update({
  id: '/historical',
  path: '/historical',
  getParentRoute: () => rootRouteImport,
} as any)
const RainfallRoute = RainfallRouteImport.update({
  id: '/rainfall',
  path: '/rainfall',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/admin/alerts',
  path: '/admin/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsAlertIdRoute = AlertsAlertIdRouteImport.update({
  id: '/alerts/$alertId',
  path: '/alerts/$alertId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsPreferencesRoute = AlertsPreferencesRouteImport.update({
  id: '/alerts/preferences',
  path: '/alerts/preferences',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assessment': typeof AssessmentRoute
  '/field-reporting': typeof FieldReportingRoute
  '/historical': typeof HistoricalRoute
  '/rainfall': typeof RainfallRoute
  '/report': typeof ReportRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/alerts/preferences': typeof AlertsPreferencesRoute
  '/alerts/': typeof AlertsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assessment': typeof AssessmentRoute
  '/field-reporting': typeof FieldReportingRoute
  '/historical': typeof HistoricalRoute
  '/rainfall': typeof RainfallRoute
  '/report': typeof ReportRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/alerts/preferences': typeof AlertsPreferencesRoute
  '/alerts': typeof AlertsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assessment': typeof AssessmentRoute
  '/field-reporting': typeof FieldReportingRoute
  '/historical': typeof HistoricalRoute
  '/rainfall': typeof RainfallRoute
  '/report': typeof ReportRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/alerts/$alertId': typeof AlertsAlertIdRoute
  '/alerts/preferences': typeof AlertsPreferencesRoute
  '/alerts/': typeof AlertsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assessment'
    | '/field-reporting'
    | '/historical'
    | '/rainfall'
    | '/report'
    | '/admin/alerts'
    | '/alerts/$alertId'
    | '/alerts/preferences'
    | '/alerts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assessment'
    | '/field-reporting'
    | '/historical'
    | '/rainfall'
    | '/report'
    | '/admin/alerts'
    | '/alerts/$alertId'
    | '/alerts/preferences'
    | '/alerts'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assessment'
    | '/field-reporting'
    | '/historical'
    | '/rainfall'
    | '/report'
    | '/admin/alerts'
    | '/alerts/$alertId'
    | '/alerts/preferences'
    | '/alerts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssessmentRoute: typeof AssessmentRoute
  FieldReportingRoute: typeof FieldReportingRoute
  HistoricalRoute: typeof HistoricalRoute
  RainfallRoute: typeof RainfallRoute
  ReportRoute: typeof ReportRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AlertsAlertIdRoute: typeof AlertsAlertIdRoute
  AlertsPreferencesRoute: typeof AlertsPreferencesRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-reporting': {
      id: '/field-reporting'
      path: '/field-reporting'
      fullPath: '/field-reporting'
      preLoaderRoute: typeof FieldReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical': {
      id: '/historical'
      path: '/historical'
      fullPath: '/historical'
      preLoaderRoute: typeof HistoricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rainfall': {
      id: '/rainfall'
      path: '/rainfall'
      fullPath: '/rainfall'
      preLoaderRoute: typeof RainfallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/admin/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$alertId': {
      id: '/alerts/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/alerts/$alertId'
      preLoaderRoute: typeof AlertsAlertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/preferences': {
      id: '/alerts/preferences'
      path: '/alerts/preferences'
      fullPath: '/alerts/preferences'
      preLoaderRoute: typeof AlertsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssessmentRoute: AssessmentRoute,
  FieldReportingRoute: FieldReportingRoute,
  HistoricalRoute: HistoricalRoute,
  RainfallRoute: RainfallRoute,
  ReportRoute: ReportRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AlertsAlertIdRoute: AlertsAlertIdRoute,
  AlertsPreferencesRoute: AlertsPreferencesRoute,
  AlertsIndexRoute: AlertsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
